package com.reactandspring.app;

import java.util.ArrayList;
import java.util.List;

public class PokemonData {
    private static List<Pokemon> pokemonList = new ArrayList<>();

    static {
        pokemonList.add(new Pokemon(1,"Bulbasaur","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/1.png"));
        pokemonList.add(new Pokemon(2," Ivysaur","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/2.png"));
        pokemonList.add(new Pokemon(3," Venusaur","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/3.png"));
        pokemonList.add(new Pokemon(4," Charmander","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/4.png"));
        pokemonList.add(new Pokemon(5," Charmeleon","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/5.png"));
        pokemonList.add(new Pokemon(6," Charizard","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/6.png"));
        pokemonList.add(new Pokemon(7," Squirtle","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/7.png"));
        pokemonList.add(new Pokemon(8," Wartortle","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/8.png"));
        pokemonList.add(new Pokemon(9," Blastoise","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/9.png"));
        pokemonList.add(new Pokemon(10," Caterpie","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/10.png"));
        pokemonList.add(new Pokemon(11," Metapod","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/11.png"));
        pokemonList.add(new Pokemon(12," Butterfree","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/12.png"));
        pokemonList.add(new Pokemon(13," Weedle","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/13.png"));
        pokemonList.add(new Pokemon(14," Kakuna","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/14.png"));
        pokemonList.add(new Pokemon(15," Beedrill","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/15.png"));
        pokemonList.add(new Pokemon(16," Pidgey","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/16.png"));
        pokemonList.add(new Pokemon(17," Pidgeotto","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/17.png"));
        pokemonList.add(new Pokemon(18," Pidgeot","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/18.png"));
        pokemonList.add(new Pokemon(19," Rattata","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/19.png"));
        pokemonList.add(new Pokemon(20," Raticate","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/20.png"));
        pokemonList.add(new Pokemon(21," Spearow","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/21.png"));
        pokemonList.add(new Pokemon(22," Fearow","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/22.png"));
        pokemonList.add(new Pokemon(23," Ekans","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/23.png"));
        pokemonList.add(new Pokemon(24," Arbok","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/24.png"));
        pokemonList.add(new Pokemon(25," Pikachu","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png"));
        pokemonList.add(new Pokemon(26," Raichu","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/26.png"));
        pokemonList.add(new Pokemon(27," Sandshrew","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/27.png"));
        pokemonList.add(new Pokemon(28," Sandslash","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/28.png"));
        pokemonList.add(new Pokemon(29," Nidoran","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/29.png"));
        pokemonList.add(new Pokemon(30," Nidorina","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/30.png"));
        pokemonList.add(new Pokemon(31," Nidoqueen","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/31.png"));
        pokemonList.add(new Pokemon(32," Nidorino","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/32.png"));
        pokemonList.add(new Pokemon(33," Nidoking","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/33.png"));
        pokemonList.add(new Pokemon(34," Clefairy","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/34.png"));
        pokemonList.add(new Pokemon(35," Clefable","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/35.png"));
        pokemonList.add(new Pokemon(36," Vulpix","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/36.png"));
        pokemonList.add(new Pokemon(37," Ninetales","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/37.png"));
        pokemonList.add(new Pokemon(38," Jigglypuff","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/38.png"));
        pokemonList.add(new Pokemon(39," Wigglytuff","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/39.png"));
        pokemonList.add(new Pokemon(40," Zubat","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/40.png"));
        pokemonList.add(new Pokemon(41," Golbat","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/41.png"));
        pokemonList.add(new Pokemon(42," Oddish","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/42.png"));
        pokemonList.add(new Pokemon(43," Gloom","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/43.png"));
        pokemonList.add(new Pokemon(44," Vileplume","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/44.png"));
        pokemonList.add(new Pokemon(45," Paras","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/45.png"));
        pokemonList.add(new Pokemon(46," Parasect","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/46.png"));
        pokemonList.add(new Pokemon(47," Venonat","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/47.png"));
        pokemonList.add(new Pokemon(48," Venomoth","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/48.png"));
        pokemonList.add(new Pokemon(49," Diglett","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/49.png"));
        pokemonList.add(new Pokemon(50," Dugtrio","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/50.png"));
        pokemonList.add(new Pokemon(51," Meowth","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/51.png"));
        pokemonList.add(new Pokemon(52," Persian","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/52.png"));
        pokemonList.add(new Pokemon(53," Psyduck","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/53.png"));
        pokemonList.add(new Pokemon(54," Golduck","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/54.png"));
        pokemonList.add(new Pokemon(55," Mankey","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/55.png"));
        pokemonList.add(new Pokemon(56," Primeape","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/56.png"));
        pokemonList.add(new Pokemon(57," Growlithe","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/57.png"));
        pokemonList.add(new Pokemon(58," Arcanine","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/58.png"));
        pokemonList.add(new Pokemon(59," Poliwag","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/59.png"));
        pokemonList.add(new Pokemon(60," Poliwhirl","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/60.png"));
        pokemonList.add(new Pokemon(61," Poliwrath","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/61.png"));
        pokemonList.add(new Pokemon(62," Abra","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/62.png"));
        pokemonList.add(new Pokemon(63," Kadabra","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/63.png"));
        pokemonList.add(new Pokemon(64," Alakazam","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/64.png"));
        pokemonList.add(new Pokemon(65," Machop","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/65.png"));
        pokemonList.add(new Pokemon(66," Machoke","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/66.png"));
        pokemonList.add(new Pokemon(67," Machamp","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/67.png"));
        pokemonList.add(new Pokemon(68," Bellsprout","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/68.png"));
        pokemonList.add(new Pokemon(69," Weepinbell","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/69.png"));
        pokemonList.add(new Pokemon(70," Victreebel","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/70.png"));
        pokemonList.add(new Pokemon(71," Tentacool","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/71.png"));
        pokemonList.add(new Pokemon(72," Tentacruel","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/72.png"));
        pokemonList.add(new Pokemon(73," Geodude","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/73.png"));
        pokemonList.add(new Pokemon(74," Graveler","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/74.png"));
        pokemonList.add(new Pokemon(75," Golem","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/75.png"));
        pokemonList.add(new Pokemon(76," Ponyta","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/76.png"));
        pokemonList.add(new Pokemon(77," Rapidash","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/77.png"));
        pokemonList.add(new Pokemon(78," Slowpoke","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/78.png"));
        pokemonList.add(new Pokemon(79," Slowbro","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/79.png"));
        pokemonList.add(new Pokemon(80," Magnemite","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/80.png"));
        pokemonList.add(new Pokemon(81," Magneton","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/81.png"));
        pokemonList.add(new Pokemon(82," Farfetch’d","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/82.png"));
        pokemonList.add(new Pokemon(83," Doduo","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/83.png"));
        pokemonList.add(new Pokemon(84," Dodrio","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/84.png"));
        pokemonList.add(new Pokemon(85," Seel","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/85.png"));
        pokemonList.add(new Pokemon(86," Dewgong","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/86.png"));
        pokemonList.add(new Pokemon(87," Grimer","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/87.png"));
        pokemonList.add(new Pokemon(88," Muk","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/88.png"));
        pokemonList.add(new Pokemon(89," Shellder","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/89.png"));
        pokemonList.add(new Pokemon(90," Cloyster","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/90.png"));
        pokemonList.add(new Pokemon(91," Gastly","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/91.png"));
        pokemonList.add(new Pokemon(92," Haunter","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/92.png"));
        pokemonList.add(new Pokemon(93," Gengar","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/93.png"));
        pokemonList.add(new Pokemon(94," Onix","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/94.png"));
        pokemonList.add(new Pokemon(95," Drowzee","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/95.png"));
        pokemonList.add(new Pokemon(96," Hypno","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/96.png"));
        pokemonList.add(new Pokemon(97," Krabby","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/97.png"));
        pokemonList.add(new Pokemon(98," Kingler","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/98.png"));
        pokemonList.add(new Pokemon(99," Voltorb","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/99.png"));
        pokemonList.add(new Pokemon(100," Electrode","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/100.png"));
        pokemonList.add(new Pokemon(101," Exeggcute","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/101.png"));
        pokemonList.add(new Pokemon(102," Exeggutor","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/102.png"));
        pokemonList.add(new Pokemon(103," Cubone","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/103.png"));
        pokemonList.add(new Pokemon(104," Marowak","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/104.png"));
        pokemonList.add(new Pokemon(105," Hitmonlee","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/105.png"));
        pokemonList.add(new Pokemon(106," Hitmonchan","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/106.png"));
        pokemonList.add(new Pokemon(107," Lickitung","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/107.png"));
        pokemonList.add(new Pokemon(108," Koffing","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/108.png"));
        pokemonList.add(new Pokemon(109," Weezing","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/109.png"));
        pokemonList.add(new Pokemon(110," Rhyhorn","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/110.png"));
        pokemonList.add(new Pokemon(111," Rhydon","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/111.png"));
        pokemonList.add(new Pokemon(112," Chansey","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/112.png"));
        pokemonList.add(new Pokemon(113," Tangela","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/113.png"));
        pokemonList.add(new Pokemon(114," Kangaskhan","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/114.png"));
        pokemonList.add(new Pokemon(115," Horsea","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/115.png"));
        pokemonList.add(new Pokemon(116," Seadra","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/116.png"));
        pokemonList.add(new Pokemon(117," Goldeen","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/117.png"));
        pokemonList.add(new Pokemon(118," Seaking","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/118.png"));
        pokemonList.add(new Pokemon(119," Staryu","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/119.png"));
        pokemonList.add(new Pokemon(120," Starmie","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/120.png"));
        pokemonList.add(new Pokemon(121," Mr. Mime","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/121.png"));
        pokemonList.add(new Pokemon(122," Scyther","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/122.png"));
        pokemonList.add(new Pokemon(123," Jynx","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/123.png"));
        pokemonList.add(new Pokemon(124," Electabuzz","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/124.png"));
        pokemonList.add(new Pokemon(125," Magmar","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/125.png"));
        pokemonList.add(new Pokemon(126," Pinsir","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/126.png"));
        pokemonList.add(new Pokemon(127," Tauros","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/127.png"));
        pokemonList.add(new Pokemon(128," Magikarp","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/128.png"));
        pokemonList.add(new Pokemon(129," Gyarados","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/129.png"));
        pokemonList.add(new Pokemon(130," Lapras","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/130.png"));
        pokemonList.add(new Pokemon(131," Ditto","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/131.png"));
        pokemonList.add(new Pokemon(132," Eevee","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/132.png"));
        pokemonList.add(new Pokemon(133," Vaporeon","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/133.png"));
        pokemonList.add(new Pokemon(134," Jolteon","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/134.png"));
        pokemonList.add(new Pokemon(135," Flareon","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/135.png"));
        pokemonList.add(new Pokemon(136," Porygon","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/136.png"));
        pokemonList.add(new Pokemon(137," Omanyte","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/137.png"));
        pokemonList.add(new Pokemon(138," Omastar","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/138.png"));
        pokemonList.add(new Pokemon(139," Kabuto","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/139.png"));
        pokemonList.add(new Pokemon(140," Kabutops","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/140.png"));
        pokemonList.add(new Pokemon(141," Aerodactyl","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/141.png"));
        pokemonList.add(new Pokemon(142," Snorlax","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/142.png"));
        pokemonList.add(new Pokemon(143," Articuno","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/143.png"));
        pokemonList.add(new Pokemon(144," Zapdos","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/144.png"));
        pokemonList.add(new Pokemon(145," Moltres","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/145.png"));
        pokemonList.add(new Pokemon(146," Dratini","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/146.png"));
        pokemonList.add(new Pokemon(147," Dragonair","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/147.png"));
        pokemonList.add(new Pokemon(148," Dragonite","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/148.png"));
        pokemonList.add(new Pokemon(149," Mewtwo","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/149.png"));
        pokemonList.add(new Pokemon(150," Mew ","https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/150.png"));

    }

    public static List<Pokemon> getPokemonList() {
        return pokemonList;
    }
}
